# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlexLayoutSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlexLayoutSample
  pod 'FlexLayout'
  pod 'PinLayout'

  target 'FlexLayoutSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlexLayoutSampleUITests' do
    # Pods for testing
  end

end
